rubyOnrails/organizador/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tasks
  resources :categories
end

rubyOnrails/organizador/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

rubyOnrails/organizador/app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id          :bigint           not null, primary key
#  name        :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Category < ApplicationRecord
  has_many :tasks

  validates :name, :description, presence: true
  validates :name, uniqueness: { case_insensitive: false }
end

rubyOnrails/organizador/app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

rubyOnrails/organizador/app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id          :bigint           not null, primary key
#  name        :string
#  description :text
#  due_date    :date
#  category_id :bigint           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Task < ApplicationRecord
  belongs_to :category
  belongs_to :owner, class_name: 'User'
  has_many :participating_users, class_name: 'Participant'
  has_many :Participants, through: :participating_users, source: :user

  validates :participating_users, presence: true

  validates :name, :description, presence: true
  validates :name, uniqueness: { case_insensitive: false }
  validate :due_date_validity

  def due_date_validity
    return if due_date.blank?
    return if due_date > Date.today
    errors.add :due_date, I18n.t('task.errors.invalid_due_date')
  end

end

rubyOnrails/organizador/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :ownedd_tasks
  has_many :participations, class_name: 'Participant'
  has_many :tasks, through: :participations
end

rubyOnrails/organizador/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  before_action :authenticate_user!, only: :home

  def set_locale
    I18n.locale = 'es'
  end
end

rubyOnrails/organizador/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :description)
    end
end

rubyOnrails/organizador/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)
    @task.owner = current_user

    respond_to do |format|
      if @task.save
        format.html { redirect_to task_url(@task), notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to task_url(@task), notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:name, :description, :due_date, :category_id)
    end
end

rubyOnrails/organizador/app/helpers/application_helper.rb
module ApplicationHelper
end

rubyOnrails/organizador/app/helpers/categories_helper.rb
module CategoriesHelper
end

rubyOnrails/organizador/app/helpers/tasks_helper.rb
module TasksHelper
end

rubyOnrails/organizador/app/views/categories/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@category) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name, label: t('.name')
    = f.input :description, label: t('.description')

  .form-actions
    = f.button :submit

rubyOnrails/organizador/app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', @category
\|
= link_to 'Back', categories_path

rubyOnrails/organizador/app/views/categories/index.html.haml
%h1 Listing categories

%table
  %thead
    %tr
      %th Name
      %th Description
      %th
      %th
      %th

  %tbody
    - @categories.each do |category|
      %tr
        %td= category.name
        %td= category.description
        %td= link_to 'Show', category
        %td= link_to 'Edit', edit_category_path(category)
        %td= link_to 'Destroy', category, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Category', new_category_path

rubyOnrails/organizador/app/views/categories/new.html.haml
%h1= t('categories.new_category')

= render 'form'

= link_to t('common.back'), categories_path

rubyOnrails/organizador/app/views/categories/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @category.name
%p
  %b Description:
  = @category.description

= link_to 'Edit', edit_category_path(@category)
\|
= link_to 'Back', categories_path

rubyOnrails/organizador/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Organizador</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%# <%= link_to 'Cerrar sesion', destroy_user_session_path, method: :delete %> %>

    <%= link_to "Tares", tasks_path %>
    <%= link_to "Categorias", categories_path %>
    
    <%= link_to "Cerrar session", destroy_user_session_path, data: {turbo_method: :delete} %>

    <%=link_to 'Sing Up', new_user_registration_path%>
    <%=link_to 'Sing In', new_user_session_path%>
    <%= yield %>
  </body>
</html>

rubyOnrails/organizador/app/views/tasks/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@task) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name
    = f.input :description
    = f.input :due_date
    = f.association :category

  .form-actions
    = f.button :submit

rubyOnrails/organizador/app/views/tasks/edit.html.haml
%h1 Editing task

= render 'form'

= link_to 'Show', @task
\|
= link_to 'Back', tasks_path

rubyOnrails/organizador/app/views/tasks/index.html.haml
%h1 Listing tasks

%table
  %thead
    %tr
      %th Name
      %th Description
      %th Due date
      %th Category
      %th
      %th
      %th

  %tbody
    - @tasks.each do |task|
      %tr
        %td= task.name
        %td= task.description
        %td= task.due_date
        %td= task.category
        %td= link_to 'Show', task
        %td= link_to 'Edit', edit_task_path(task)
        %td= link_to 'Destroy', task, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Task', new_task_path

rubyOnrails/organizador/app/views/tasks/new.html.haml
%h1 New task

= render 'form'

= link_to 'Back', tasks_path

rubyOnrails/organizador/app/views/tasks/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @task.name
%p
  %b Description:
  = @task.description
%p
  %b Due date:
  = @task.due_date
%p
  %b Category:
  = @task.category

= link_to 'Edit', edit_task_path(@task)
\|
= link_to 'Back', tasks_path