rubyOnrails/my_app/config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :books
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'hola', to: 'welcome#hello'
end

rubyOnrails/my_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

rubyOnrails/my_app/app/models/book.rb
class Book < ApplicationRecord
end

rubyOnrails/my_app/app/models/pet.rb
class Pet < ApplicationRecord
end

rubyOnrails/my_app/app/models/user.rb
class User < ApplicationRecord
end

rubyOnrails/my_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

rubyOnrails/my_app/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    binding.pry
    @books = Book.all
    # byebug
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :author, :description, :isbn, :pages_count)
    end
end

rubyOnrails/my_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    # I18n.local = 'es'
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :address, :about_me, :phone)
    end
end

rubyOnrails/my_app/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def hello
    @variable = Pet.first.name
    @credentials =  Rails.application.credentials.hello
  end
end

rubyOnrails/my_app/app/helpers/application_helper.rb
module ApplicationHelper
end

rubyOnrails/my_app/app/helpers/books_helper.rb
module BooksHelper
end

rubyOnrails/my_app/app/helpers/users_helper.rb
module UsersHelper
end

rubyOnrails/my_app/app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <p>
    <strong>Title:</strong>
    <%= book.title %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= book.author %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= book.description %>
  </p>

  <p>
    <strong>Isbn:</strong>
    <%= book.isbn %>
  </p>

  <p>
    <strong>Pages count:</strong>
    <%= book.pages_count %>
  </p>

</div>

rubyOnrails/my_app/app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :author, style: "display: block" %>
    <%= form.text_field :author %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :isbn, style: "display: block" %>
    <%= form.text_field :isbn %>
  </div>

  <div>
    <%= form.label :pages_count, style: "display: block" %>
    <%= form.number_field :pages_count %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

rubyOnrails/my_app/app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", @book %> |
  <%= link_to "Back to books", books_path %>
</div>

rubyOnrails/my_app/app/views/books/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Books</h1>

<div id="books">
  <% @books.each do |book| %>
    <%= render book %>
    <p>
      <%= link_to "Show this book", book %>
    </p>
  <% end %>
</div>

<%= link_to "New book", new_book_path %>

rubyOnrails/my_app/app/views/books/new.html.erb
<h1>New book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Back to books", books_path %>
</div>

rubyOnrails/my_app/app/views/books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @book %>

<div>
  <%= link_to "Edit this book", edit_book_path(@book) %> |
  <%= link_to "Back to books", books_path %>

  <%= button_to "Destroy this book", @book, method: :delete %>
</div>

rubyOnrails/my_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

rubyOnrails/my_app/app/views/users/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@user) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :first_name, label: t('users.first_name')
    = f.input :last_name, label: t('.last_name')
    = f.input :about_me, label: t('.about_me')
    = f.input :phone, label: t('.phone')

  .form-actions
    = f.button :submit, label: t('.submit')

rubyOnrails/my_app/app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

rubyOnrails/my_app/app/views/users/index.html.haml
%h1 Listing users

%table
  %thead
    %tr
      %th First name
      %th Last name
      %th Address
      %th About me
      %th Phone
      %th
      %th
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td= user.first_name
        %td= user.last_name
        %td= user.address
        %td= user.about_me
        %td= user.phone
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User', new_user_path

rubyOnrails/my_app/app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

rubyOnrails/my_app/app/views/users/show.html.haml
%p#notice= notice

%p
  %b First name:
  = @user.first_name
%p
  %b Last name:
  = @user.last_name
%p
  %b Address:
  = @user.address
%p
  %b About me:
  = @user.about_me
%p
  %b Phone:
  = @user.phone

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path

rubyOnrails/my_app/app/views/welcome/hello.html.haml
Como estas?
= @variable
= @credentials